FROM node:20.11.1

COPY package.json package-lock.json ./
RUN npm i

COPY hardhat.config.ts hardhat.config.ts
COPY ./precompiled ./precompiled
COPY ./contracts ./contracts
COPY ./tsconfig.json ./
RUN npm run compile

COPY flatten.sh flatten.sh
RUN npm run flatten

COPY deploy.sh deploy.sh
COPY ./deploy ./deploy
COPY ./test ./test
COPY ./e2e-tests ./e2e-tests
