name: Tests
on: [push, pull_request]
env:
  CI: true

jobs:
  test:
    name: Node ${{ matrix.node }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    outputs:
      session-id: ${{ steps.start-session.outputs.session-id }}
      session-endpoint: ${{ steps.start-session.outputs.session-endpoint }}

    strategy:
      fail-fast: false
      matrix:
        node: [20]
        os: [ubuntu-latest]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: npm ci # switch to `npm ci` when Node.js 6 support is dropped

      - name: Create typechain types
        run: npx hardhat compile

      - name: Run compile (+lint)
        run: npm run compile

      - name: Run tests
        run: npm run test
